version: '3.3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db

  redis:
    image: redis:alpine

  sqli:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: |
      python run.py
